### ISSUE TITLE
Changing keynote title

### ISSUE THREAD

**Issue by dret** [RESTFest/2016.restfest.org#1]
can we change it to "Deconstructing the Web", please? thanks! also, if possible, please link to: http://dret.net/lectures/restfest-2016/ (these are the slides, i will refresh them later today...)

**Comment by mamund** [comment]
fixed #1

**Comment by dret** [comment]
On 2016-09-16 10:13, Mike Amundsen wrote:

> Closed #1 https://github.com/RESTFest/2016.restfest.org/issues/1.

that was quick. thanks!

**Comment by dret** [comment]
i think now i found the place, #2 should fix it on the site.
